### ISSUE TITLE
Colons in comments appear in  the json output

### ISSUE THREAD

**Issue by BjoernSchilberg** [Jonarod/markty-TOML#1]
Hej,
it seems that comments containing a  colon `:` are not handle correct. Comments like

```toml
# Comments https://en.wikipedia.org/wiki/TOML
# Comments: test
```

appear in the json output:

```javascript
"types": {
        "# Comments https": "//en.wikipedia.org/wiki/TOML",
        "# Comments": "test",
...
}
```

See also https://jsfiddle.net/sL9ssuch/5/ for a working example.

I would have expected these comments to be ignored.

I'm using it wrong or do I misunderstood something?

**Comment by Jonarod** [comment]
Hey !
Unfortunately, like posted in the README:
> The nature of markty-TOML makes comments out of the scope and are unlikely to be implemented (if compulsory, comments can be set as a normal entries anyway...)

I may think about making comments available on a per line basis, like 
```
# this is a comment
```
but proper v0.4 comments will most probably never be integrated, like:
```
key = "value" # this comment is invalid
```

**Comment by Jonarod** [comment]
If you inspect the code you will understand that comments are not handled at all. The fact that 
```
# This is a comment
``` 
is discarded is because IT IS NOT RECOGNIZED AS A PROPER KEY/VALUE PAIR, rather than because it is in fact a comment...
That being said, if one introduces a `=` or `:`, the parser will recognize a key/value pair.

For better understanding try this:
```
# This is a comment
+ So is this
- And this one
and even this
% or this...
``` 
==> `markty-TOML` does not support comments, but it will not include lines that do not look like key/value pairs.

Now like I said earlier, I may introduce the possibility to have a proper escape defined by `#`, allowing single line comments preventing any of `=` and `:` to be interpreted as key/value pairs.

**Comment by Globegitter** [comment]
@Jonarod Are you still planing on implementing this? That would make this toml parser perfect for our use-cases as all we need is line comments and it is much faster than anything else I have tested.

**Comment by Jonarod** [comment]
Hey!
Let me see what I can do over this weekend and I'll let you know :)

**Comment by Jonarod** [comment]
@Globegitter added single line comments. Check it out ;)
